opcache.max_accelerated_files = 20000
opcache.memory_consumption = 256
realpath_cache_size = 4096K
realpath_cache_ttl = 600

[memcache]
extension = memcache.so

[xdebug]
zend_extension = xdebug.so
xdebug.idekey = php_customized_key
xdebug.mode = coverage,develop,debug
xdebug.start_with_request = yes
xdebug.client_host = 127.0.0.1
xdebug.client_port = 9000
xdebug.log_level = 0
xdebug.max_nesting_level = 16384
